### ISSUE TITLE
Add gpu testing in CI

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank2#143]
See https://betterprogramming.pub/gpu-ci-tests-using-kaggle-90e4f88a43b3.

**Comment by gcroci2** [comment]
Blocked by https://github.com/namiyousef/colab-utils/issues/12

**Comment by gcroci2** [comment]
The problem is that the Kaggle runner uses Python 3.7. It doesn't seem like they provide support for other python versions, so this will remain an open issue. See [this issue](https://github.com/namiyousef/action-kaggle-gpu-test/issues/4) from the author of the action.

**Comment by DaniBodor** [comment]
Note that test_trainer alsready has a `test_cuda` function. Not sure if this helps at all?

**Comment by gcroci2** [comment]
> Note that test_trainer alsready has a `test_cuda` function. Not sure if this helps at all?

Yes but it's never actually tested because the default environment of GitHub actions does not have cuda installed.
