### ISSUE TITLE
Using a pdb file containing only one chain gives unexpected results

### ISSUE THREAD

**Issue by DTRademaker** [DeepRank/deeprank2#185]
Hello,

I cannot generate correct edges. Not only are they not symmetrical (if there is an edge(0,1) there should also be an edge(1,0)), the edges calculates are completely different when I run the exact same script on the exact same pdb. Different order and different edges. I put the code and pdb in the attachment including a screenshot of the edges at multiple runs

Daniel

[vb1.zip](https://github.com/DeepRank/deeprank-core/files/9577852/vb1.zip)

**Comment by DTRademaker** [comment]
Hi Giulia, 

Thank you for checking. And yes I know it was not originally developed for this, Li tasked me me with implementing my GNN powered structural alignment algorithm in DeepRank to proof how versatile DeepRank is. Since I only use a single chain and connect nodes within a certain radius, it is actually similar to having a protein-protein interaction/interface with itself. I was able to build my custom query and feature classes/functions but I came across the errors I mentioned earlier. Starting with the 'mirroring': it is nice that the 'mirroring' is done elsewhere, but this assumes the edges are symmetrical, which is not always true. For example, one feature I use is to check if one node is earlier in the sequence than the nodes it is connected to, these edge-features are different for the edge A-B than the edge B-A and can't simply be 'copied'. I think the whole graph should therefore be in the hdf5, but that is of course between you and Li and Coos. My main concern was about the fact that if I run the script 3 times I get 3 different graphs with sometimes different edges (for example the edge between nodes 0 and 3 in my screenshot only appears in 2 of the 3 runs). This is weird to my because I expect this to be a deterministic process right?

**Comment by gcroci2** [comment]
I agree that the process should be completely deterministic. @cbaakman I couldn't find a reason for this, maybe you can help?

**Comment by gcroci2** [comment]
For the mirroring and the graphs built, it depends on what we want this package to do.
- I would say that it would be better to have the "real" graph in the hdf5 file, and not only in the HDF5DataSet instance, like @DTRademaker is saying.
- Regarding the symmetry in edges, it really depends on how many use cases will need such an asymmetry in edge-features. 

What are your thoughts? @LilySnow @cbaakman

**Comment by LilySnow** [comment]
Hello all, nice discussions. How much effort is needed to include the directed graph? If it is not much trouble, we could consider adding an option `directed_graph = False`, so that Manon's paper for DeepRank-GNN could be replicated easily.

**Comment by gcroci2** [comment]
Can we easily implement the undirected graphs? @cbaakman

**Comment by cbaakman** [comment]
Deeprank does not keep track of the orders of nodes or edges when building a graph. These are simply stored as a python dictionary. Why the order is different every time, I don't know. We could change this by using a sorting function, if it matters.

Making unidirected graphs is difficult. You could implement a second type of edge, that is unidirectional. But you'd have to change many functions as well, since those all assume that edges are direction-less.

**Comment by cbaakman** [comment]
Having the real graph in the hdf5 file would be an option indeed. In such case one would have to change 2 functions: the graph_to_hdf5 writer and the hdf5_to_graph reader.

**Comment by gcroci2** [comment]
> Having the real graph in the hdf5 file would be an option indeed. In such case one would have to change 2 functions: the graph_to_hdf5 writer and the hdf5_to_graph reader.

Would you have time to implement this @cbaakman not urgently?

**Comment by gcroci2** [comment]
Duplicate of #233
