### ISSUE TITLE
Include all PDB fields as metafeatures

### ISSUE THREAD

**Issue by KevinVG207** [DeepRank/deeprank2#225]
For my project I will eventually need to fish all of the backbone atoms out of the HDF5 files created by deeprank. As I looked at some of the output of deeprank, I noticed that the _name metafeature for atoms also includes PDB name, the chain and residue index. I'm not sure how this relates to the name of the atom. As it is currently, I would need to manually go through the _name metafeature of an atom and split out the atom name. (N, C, CA etc.)

This got me wondering if maybe all data fields from atoms from a PDB could be added as metafeatures (see [PDB format](http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM) for the data fields), to be used for processing the data later since it's hard to map the atoms back to the original PDB. (As far as I'm aware.) Basically, it would be useful to have the PDB atom data stored in the final HDF5. Maybe in groups like _serial, _name, _altLoc, _resName etc.

Let me know what you think.

**Comment by DaniBodor** [comment]
Good idea to pull out all of the info from the PDB file, and great that you sent that link (I'd been looking for something that explains exactly what is in these PDB files and had only found something that partially answered it for me).

> As it is currently, I would need to manually go through the _name metafeature of an atom and split out the atom name. (N, C, CA etc.)
Why do you have to go through manually as opposed to writing a script that gets this data for you? Also, are you interested in the exact atom name (CA, SD, CG1, N, etc) or just in the the atomic element (C, S, N)? If you just want the element, then it is currently already a true feature (atom_type, which is one-hot encoded as C = 1, O = 2, N = 3, S = 4, P = 5, H = 6)

>  As I looked at some of the output of deeprank, I noticed that the _name metafeature for atoms also includes PDB name, the chain and residue index. I'm not sure how this relates to the name of the atom.

The _name metafeature is the name of the node, not of the atom. The idea of this feature is that if you read it with human eyes, you know exactly which atom that node represents without the need for additional context, not only what the atom name is.

BTW, I am curious to know what the additional information of atom name in the PDB file represents, apart from the atomic element. Do you know this?
