### ISSUE TITLE
Evaluate storage of grid features values per chain

### ISSUE THREAD

**Issue by cbaakman** [DeepRank/deeprank2#344]
I noticed that the old deeprank stores grid feature values per chain, for protein-protein interactions. The currect deeprank-core doesn't do that. If we were to apply this to deeprank-core, we need to somehow make the mapping methods treat protein-protein interface graphs differently.

I'm not sure how much this difference affects the performance of deeprank.

**Comment by gcroci2** [comment]
Is this still an issue? Did we take any decisions here? @cbaakman

**Comment by cbaakman** [comment]
> Is this still an issue? Did we take any decisions here? @cbaakman

No decisions were made on this topic yet.
