### ISSUE TITLE
Add documentation for Variant queries

### ISSUE THREAD

**Issue by DaniBodor** [DeepRank/deeprank2#371]
DeepRank core generally allows you to predict 2 different things: protein-protein-interactions (PPIs) or something about variant residues.

All documentation in README is focussed on PPIs. It is unclear what the purpose of the Variant queries is and how to use this. We should add an explanation of this to the README.

Also, development of the package is done (almost) exclusively with PPIs in mind, given that it is unclear what the purpose of the variant queries is. It would really help if this was clarified so that both types of projects can be taken into account during development.

**Comment by gcroci2** [comment]
Blocked by #377

**Comment by gcroci2** [comment]
We will keep PPIs only on the readme and getstarted, but in #459 we're developing detailed tutorials for variants.

**Comment by DaniBodor** [comment]
> We will keep PPIs only on the readme and getstarted, but in #459 we're developing detailed tutorials for variants.

Not sure whether that is already happening in #459 (I think yes), but we should at least mention in the readme that this is the case.
I also think that means we can close this issue once #459 is closed.

**Comment by gcroci2** [comment]
> > We will keep PPIs only on the readme and getstarted, but in #459 we're developing detailed tutorials for variants.
> 
> Not sure whether that is already happening in #459 (I think yes), but we should at least mention in the readme that this is the case.

Yep, we do it [here](https://github.com/DeepRank/deeprank-core/blob/435_add_tutorials_variants_gcroci2/README.md#quick-start)
