### ISSUE TITLE
Fix hydrogens unkown to the forcefield

### ISSUE THREAD

**Issue by Max1461** [DeepRank/deeprank2#380]
@LilySnow @gcroci2 @DaniBodor 
I run into a situation that when I use queries.process() to make and save my graph(s) the following type of warning messages are printed for several hydrogens atoms:

```
is unknown to the forcefield; charge is set to 0.0
is unknown to the forcefield; vanderwaals_parameters set to (0.0, 0.0, 0.0, 0.0)
```

The test situation in which this occurs is when I use the following pdb file(I have changed the extension otherwise I could not upload it to git)
[1AKJ.txt](https://github.com/DeepRank/deeprank-core/files/10924931/1AKJ.txt)

The hydrogen atoms are then added to this pdb file using:

`reduce -FLIP -Quiet $pdbFL > $pdbFL.reduce_flip`

Resulting in the following pdb file with hydrogens present:
[1AKJ.txt](https://github.com/DeepRank/deeprank-core/files/10924963/1AKJ.txt)

From this pdb file with added hydrogens a micro-environment is selected and written to a new pdb file, in this case:
[1AKJ_1_ILE.txt](https://github.com/DeepRank/deeprank-core/files/10924971/1AKJ_1_ILE.txt)

This pdb structure is added to
`queries = QueryCollection()` 

And the graph is then generated and saved with

`queries.process()`

During the process step the warning message is printed, which i have added in the following text file:
[warning_message.txt](https://github.com/DeepRank/deeprank-core/files/10924992/warning_message.txt)

This occurs because the hydrogen naming conventions in the pdb that has the hydrogens added through reduce do not match the hydrogen naming conventions present in the forcefield topology file used by DeepRank core.

I have already discussed this issue today during a meeting with @LilySnow and have made this issue after this. Hopefully I have provided enough information through the files, and if not I would gladly help out further.

**Comment by gcroci2** [comment]
Many thanks @Max1461, we'll look soon further into this :)

**Comment by DaniBodor** [comment]
I believe that this will be dealt with in #393
