### ISSUE TITLE
Use openMM to redefine the forcefield

### ISSUE THREAD

**Issue by DaniBodor** [DeepRank/deeprank2#393]
This has multiple advantages:
- allows optional (and correct) generation of hydrogens in pdb structures based on predicted protonation state
- allows determining 1-3 and 1-4 pairings for nonbond energy calculation
- more accurate/useful/?? forcefield?

**Comment by gcroci2** [comment]
Following up on this after today's meeting, we decided to give high priority to modifying the package to be able to read in pdb files with hydrogens generated with @joaomcteixeira's code.

**Comment by gcroci2** [comment]
> Following up on this after today's meeting, we decided to give high priority to modifying the package to be able to read in pdb files with hydrogens generated with @joaomcteixeira's code.
> 
> * Did I understand correctly that you used amber forcefield instead of OPLS, the one we have in the deeprank2 package @joaomcteixeira?
 
OPLS is old, so it's recommended to replace it

**Comment by gcroci2** [comment]
> Also, @LilySnow asked to use @joaomcteixeira's code to calculate pairwise energies such as electrostatic and van der waals after we updated the forcefield. Reflecting on it now, to me it's not clear why is this needed, since we've already these features. For sure I'd need more context.

We need Joao's code because we will not use anymore the param file for vdw, but we will use OpenMM directly for computing pair-wise energies. Then I would need @joaomcteixeira to indicate to us where the code precisely is.

**Comment by joaomcteixeira** [comment]
Hi,

Yes, all the code I did is in the https://github.com/DeepRank/pdbprep repository.

Regarding interface atom-atom pairwise energy calculation using OpenMM it is all in the https://github.com/DeepRank/pdbprep/pull/12, as you mentioned. Let me know if something is not clear in the documentation of the code or the code itself.

Best wishes,

**Comment by gcroci2** [comment]
This is done in pdbprep repository, but deeprank2 still uses OPLS forcefield without OpenMM.
