### ISSUE TITLE
Evaluate to add a conda release

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank2#440]
Right now we're using Pypi release only, but we have many dependencies that the user needs to install in conda. Either we wrap them up in a .sh script (see NPLinker package [example](https://github.com/NPLinker/nplinker/blob/main/bin/install-nplinker-deps)) or we evaluate to release the package on conda to decrease the steps that the user needs to do to install the package.

**Comment by DaniBodor** [comment]
will be solved in #475
