### ISSUE TITLE
Add torsion angle feature for residues (calculated from the backbone)

### ISSUE THREAD

**Issue by DanLep97** [DeepRank/deeprank2#448]
**Is your feature request related to a problem? Please describe.**
Encoding physical constraints and making the predictor aware of these constrains is hard. Nevertheless it plays an important role in specific tasks. In the case of protein-peptide interaction, a very constrained conformation would either facilitate or make the interaction more cumbersome.

**Describe the solution you'd like**
Dihedral angles present in the amino-acid backbone chain (torsion angles phi, psi and omega) give a clue how constrained a conformation is with regards to neighboring residues in sequence and space.

**Describe alternatives you've considered**
Other tools use angles directly between residues but the atomic context gives a richer representation (vector of 3 values for each residue) and is more biologically relevant. 

**Additional context**
![image](https://github.com/DeepRank/deeprank-core/assets/34490977/a92a1e59-d367-474c-a411-8248611a6d55)

**Checks for the developer**
After having implemented the request, please remember to: 
- [ ] Add all the necessary tests. Make sure that the parameter functionality is well tested, from all points of views.
- [ ] Add the proper documentation to the source code (docstrings).
- [ ] Add the proper documentation to the readme. Examples about how using the new feature should be clear and easy to follow.

**Comment by gcroci2** [comment]
What's the status of this issue? @DanLep97
