### ISSUE TITLE
Clarify `distance_cutoff` across different `Query` classes

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank2#460]
While developing tutorials for variants (PR #435) I noticed that the logic behind the `distance_cutoff` parameter across different query types is not very linear and clear, at least from my perspective. 

In variant query classes, the residues/atoms of interest are selected with the radius (via `get_surrounding_residues`) around the variant. 

In PPIs query classes, `distance_cutoff` is used for `_load_ppi_atoms` (I guess selecting the interface, within the distance cutoff).

Then, in all queries logic, `build_residue_graph` (or `build_atomic_graph`) builds a graph of the selected elements, and takes the distance cutoff as input, which in `build_residue_graph` is defined as the *shortest* interatomic distance between two residues.
- Actually, looking into `build_residue_graph`, then distances < the distance cut off are selected, making the cutoff distance actually the max and not the min. 
- `build_residue_graph` (and `build_atomic_graph`) selects distances < the distance cut off, but at least for PPIs this should have been done already in `_load_ppi_atoms` (and for variants in `get_surrounding_residues`). Can we remove this parameter from `build_residue_graph`?
- `Graph` class has `cutoff_distance` param as well, but again I don't think it's needed (never used in the `Graph` class).

Your feedback here would be very useful :) @DaniBodor

**Comment by DaniBodor** [comment]
Yeah, I remember looking into this before and I was also confused by it. I think in the end I came to the conclusion that it actually does make sense how it is done now, but don't remember exactly.
I will look at it again and at the very least we should add comments or something so that we don't keep second guessing why it is done the way it is.

**Comment by DaniBodor** [comment]
Looking into it again, this is what I think is happening (it is a little bit clearer in [this](https://github.com/DeepRank/deeprank2/tree/480_new) branch, although that is still a work in progress.)

**For variant queries:**
- `radius` is used by `get_surrounding_residues` to determine which residues to include in the graph.
  - any residue that has an atom within the `radius` is included, irrespective of resolution.
- `distance_cutoff` is used by `build_residue_graph` or `build_atomic_graph` to determine which pair of nodes will form an edge between them.
  - for residue graphs: any two residues that contain an atom within `distance_cutoff` will generate an edge
  - for atomic graphs: any two atoms within `distance_cutoff` will generate an edge
- I think this is the desired behavior of how these parameters should work.
  - Their naming and documentation should definitely be improved to reflect their function better.

**For PPI queries:**
- `radius` parameter does not exist.
- `distance_cutoff` is used for two separate things that don't necessarily need to be connected
  - it is first used by `get_contact_atoms` (which in turn uses it a function of same name from pdb2sql). I believe it uses this to determine the maximum distance between two residues of opposing chains to include in the structure.
    - if I understand the usage correctly, this is more or less the equivalent of what `radius` is above.
  - it is then used again by by `build_residue_graph` or `build_atomic_graph` in the same way as above.
- I think it would make sense to make PPI queries follow the logic of variant queries, where `radius` can be set separately from `cutoff_distance`, as there is no inherent reason why these must have the same value.
