### ISSUE TITLE
Fix link in TUTORIAL.md

### ISSUE THREAD

**Issue by elboyran** [DeepRank/deeprank2#462]
The link to the tutorials are broken (extra \tutorials folder in path) in [TUTORIAL.md](https://github.com/DeepRank/deeprank-core/blob/main/tutorials/TUTORIAL.md)

**Comment by gcroci2** [comment]
> The link to the tutorials are broken (extra \tutorials folder in path) in [TUTORIAL.md](https://github.com/DeepRank/deeprank-core/blob/main/tutorials/TUTORIAL.md)

Indeed, thanks for reporting it. It will be fixed in #459.
