### ISSUE TITLE
Is `_get_atom_node_key` obsolete?

### ISSUE THREAD

**Issue by DaniBodor** [DeepRank/deeprank2#490]
This method is part of `SingleResidueVariantAtomicQuery` class, but does not seem to be used anywhere. @cbaakman , do you know if it is still needed for anything?

**Comment by DaniBodor** [comment]
will do

**Comment by gcroci2** [comment]
Can we close this? @DaniBodor

**Comment by DaniBodor** [comment]
yes, must have missed this when closing #480
