### ISSUE TITLE
Add performances comparisons with previous packages

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank2#500]
Table implemented in PR #493 shows the timings obtained for generating graphs/graphs+grids, atomic resolution, with all features except for the ones in the `conservation` module, because we don't have the pssm files for the data in the tutorials (for computing the performances of deeprank2, I used the raw data available at [this address](https://zenodo.org/record/8349335)).

We need some discussion here:
1. Is this a satisfying way of showing performances? Do we need to generate **all** the features possible (by adding `conservation` module features), and to add performances for residue resolution as well? 
2. How do we do a fair comparison with the previously developed packages? Features are different in number and in how they are calculated, so if we use all features in all packages we can't know if the comparison is fair. Maybe we could just pick a couple of them which are the same in all packages (e.g., distance, residue type)?

When we'll have clearer ideas/plans about 1. and 2., compare deeprank2 with:
- deeprank
   - [ ] PPIs, grid
- deeprank-gnn
   - [ ] PPIs, graph
- deeprank-mut
   - [ ] variants, grid

**Comment by gcroci2** [comment]
How would you advice to proceed here, especially for question 2.? @sonjageorgievska, @DaniBodor

**Comment by DaniBodor** [comment]
I don't have a great idea about this, apart from just doing a "not fair" comparison and being open about it and explaining the differences.

**Comment by gcroci2** [comment]
> I don't have a great idea about this, apart from just doing a "not fair" comparison and being open about it and explaining the differences.

Actually I agree, I also think this is the only realistic option we have.
