### ISSUE TITLE
h5x didn't work

### ISSUE THREAD

**Issue by Lsz-20** [DeepRank/deeprank2#578]
I have followed to install the h5xplorer in Deeprank-GNN,but it cannot work well to show the graphs?
<img width="858" alt="image" src="https://github.com/DeepRank/deeprank2/assets/60343452/48ad465f-0063-4e78-bb4b-74d606f494ff">

**Comment by cbaakman** [comment]
What error are you getting?
Didn't the clustering succeed?

**Comment by Lsz-20** [comment]
Yes,I tried the test data of 1ATN_10W,but it didn't show me any graph

**Comment by Lsz-20** [comment]
Is due to server browser issues that has been resolved Thanks
