### ISSUE TITLE
convert PSSM from 3dcons to deeprank

### ISSUE THREAD

**Issue by Lsz-20** [DeepRank/deeprank2#581]
Hello, I try to convert the download pssm files from 3dcons with DeepRank_GNN/deeprank_gnn/tools/pssm_3dcons_to_deeprank.py, but it seem no result files?

**Comment by gcroci2** [comment]
Hi @Lsz-20! The script you're referring to is not part of this new version of the repository, but if you provide us with more details (e.g., the PSSM files you're using, how you're running the script, the OS) we can try to help you.
