### ISSUE TITLE
Manage/set dependencies versions

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank2#607]
Given that active development on this project slowed down, we need to make the dependencies more reliable in terms of version used during the installation, including in the CI. The easiest way to go consists in just fixing dependency versions. However, it's good to try to avoid falling too far behind and encountering security issues. 

I suggest:
- [x] To create a requirements file after having re-installed everything in a brand new env, to be sure we are up-to-date with the latest versions working of the various packages (`pip freeze > requirements.txt`); We know that these versions work for sure. 
- [x] Fix versions for critical dependencies (e.g., PyTorch) and use version ranges for less critical ones (e.g., numpy).

I think it's good to first fix #559 (dropping entirely the conda thing) and then go for this one.

**Comment by DaniBodor** [comment]
Maybe part of this could also be to work with a single env file. The only difference I think is that the docker calls a separate file to install the local package. If there's a way to do this outside the env file, then we can get by with a single one.

(or is this part of #559)?

**Comment by gcroci2** [comment]
> Maybe part of this could also be to work with a single env file. The only difference I think is that the docker calls a separate file to install the local package. If there's a way to do this outside the env file, then we can get by with a single one.
> 
> (or is this part of #559)?

Yeah I think this is part of #559, we will look into this possibility there
