### ISSUE TITLE
Remove types from docstrings

### ISSUE THREAD

**Issue by DaniBodor** [DeepRank/deeprank2#627]
According to the [Google convention](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html), functions with type hinted arguments do not need to have the types inside the docstring (see example below). I think the same is true for whether or not they are optional.

Currently, most of our docstrings do have the types (and optionality) annotated, despite them all being type hinted already. This makes them a bit clunky and lengthy.

Do we want to update these or leave them as is?

```python
def function_with_pep484_type_annotations(param1: int, param2: str) -> bool:
    """Example function with PEP 484 type annotations.

    Args:
        param1: The first parameter.
        param2: The second parameter.

    Returns:
        The return value. True for success, False otherwise.
    """
```

**Comment by gcroci2** [comment]
It's a nice improvement :) I'd say it's not a priority and as it is does not limit the usage or the clarity of the docs, but up to you if you wish to pick this up.

**Comment by DaniBodor** [comment]
For some reason the issues associated to my PRs are not automatically closing when the PR gets merged. @gcroci2 , any idea why?

**Comment by gcroci2** [comment]
I think that the old project kanban had automation broken, but this new one seems to work @DaniBodor
