### ISSUE TITLE
Migrate kanban boards to new Projects

### ISSUE THREAD

**Issue by DaniBodor** [DeepRank/deeprank2#629]
"Projects (classic)", which we are now using for the kanban boards, will deprecate by end of August. See [here](https://github.blog/changelog/2024-05-23-sunset-notice-projects-classic/).
There is a button to migrate it over. Might not be worthwhile for the current board, but at least the SSP board should be migrated.

**Comment by gcroci2** [comment]
<img width="700" alt="image" src="https://github.com/user-attachments/assets/c6d49c7c-d1b2-4088-bfe0-ca9f44b9b08b">

From here it seems that if we don't do it it's done automatically. If that's the case I'd just wait for the automatic migration and in case edit that one @DaniBodor

**Comment by gcroci2** [comment]
Actually it was super fast, done :D @DaniBodor
