### ISSUE TITLE
Is pretrained model released?

### ISSUE THREAD

**Issue by Tizzzzy** [DeepRank/deeprank2#638]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to train the model from scratch.

**Describe the solution you'd like**
Can you release the pretrain model weight?

**Comment by gcroci2** [comment]
Hi @Tizzzzy,

Thank you for your suggestion!

The core objective of this package is to offer maximum flexibility in training models tailored specifically to your needs, whether it’s customizing features, neural network architectures, or targets for your unique application. As such, the focus isn't primarily on providing pretrained models. It’s important to note that these models are typically effective only when your data and prediction targets closely match those used in the pretrained models themselves, which is very often not the case.

However, we do recognize that having access to pretrained models could be valuable in certain scenarios. For some of our previously developed applications, there is ongoing discussion about adding pretrained models (see issue #602). The challenge, however, is that these models were trained using an earlier version of the package (see for example [here](https://github.com/DeepRank/Deeprank-GNN/tree/master/paper_pretrained_models)), and we currently lack the resources to retrain them with DeepRank2.

For your information, we are in the process of publishing a paper on predicting the binding affinity of pMHCI complexes, using models developed with DeepRank2. Once the paper and related data are published, we plan to make these pretrained models available as well.
