### ISSUE TITLE
Question about the training data

### ISSUE THREAD

**Issue by Tizzzzy** [DeepRank/deeprank2#639]
Hi author,
If I am planning to train the GNN model only for general purpose use. Is there a training data that I can use directly?
Currently I see some data in `tests/data` path, but I don't know which training data I should use.
Thank you for your help

**Comment by gcroci2** [comment]
Hi @Tizzzzy,

Thank you for your question!

Could you clarify what you mean by "general purpose"? Our framework is based on a supervised learning mechanism, which means that to train a model, you'll need to provide labeled data (whether for classification or regression) and specify the task you're aiming to accomplish.

To help you get started, we've developed [some tutorials](https://github.com/DeepRank/deeprank2/blob/main/tutorials/TUTORIAL.md), including a training notebook that you can find [here](https://github.com/DeepRank/deeprank2/blob/main/tutorials/training.ipynb). This notebook includes [a link to sample data](https://zenodo.org/records/8349335) that you can download and use to train an example model. However, please note that this sample data is intended for educational purposes and may not yield meaningful results for real-world applications.

If you're looking to train a model with more substantial outcomes, you'll need to gather specific data relevant to your intended use case, such as PDB files, along with the corresponding labels (targets) that align with your task, whether it's classification, regression, or another application.

We do have plans to release some of our application-specific data soon. However, this data will be tailored to a particular use case and might not be suitable for general-purpose training. The main goal of the package is not to provide general-purpose data but to enable users to train models on their own specific datasets.
