### ISSUE TITLE
Question about training

### ISSUE THREAD

**Issue by Tizzzzy** [DeepRank/deeprank2#644]
Hi author,
Huge fan of your work. Currently, I am planning to train a model using the tutorial [here](https://github.com/DeepRank/deeprank2/blob/main/tutorials/TUTORIAL.md). However, I see there are two tasks, PPIs and SRVs. I am not sure which one I should use.
My downstream task is that, after I trained a GNN model, I want to input **only one protein pdb file** at a time, and then extract this protein's latent representation from the model. Based on my downstream task, which training tutorial do you recommend me to do?
Thank you so much for your help

**Comment by gcroci2** [comment]
Hi @Tizzzzy, 
To clarify, PPIs and SRVs are not tasks but rather concepts that are explained in detail within the documentation and the tutorials. I highly recommend carefully reading them to better understand these concepts.
